In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

# Q1

In [2]:
data_cus=pd.read_csv('AWCustomers.csv')
data_sales=pd.read_csv('AWSales.csv')

In [3]:
data_cus.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [4]:
data_sales.columns

Index(['CustomerID', 'BikeBuyer', 'AvgMonthSpend'], dtype='object')

In [5]:
#to avoid repetition when we concatenate both datasets
data_sales.drop(['CustomerID'],axis=1,inplace=True)

In [6]:
df=pd.concat([data_cus,data_sales],axis=1)

In [7]:
df

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated,BikeBuyer,AvgMonthSpend
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,M,M,1,3,0,1,81916,2017-03-06,1.0,50.97
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,M,M,1,2,1,2,81076,2017-03-06,1.0,53.11
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,F,S,0,3,0,0,86387,2017-03-06,1.0,54.08
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,M,M,1,2,1,2,61481,2017-03-06,1.0,56.93
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,M,S,1,1,0,0,51804,2017-03-06,1.0,55.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,NaN,Grace,C,Bailey,NaN,6627 Camelback Ct.,NaN,Coronado,California,...,F,M,0,1,0,2,52953,2017-03-06,NaN,NaN
18357,11459,NaN,Tasha,NaN,Deng,NaN,9627 Kendall Rd,NaN,Port Macquarie,New South Wales,...,F,S,0,2,0,0,60992,2017-03-06,NaN,NaN
18358,12160,NaN,Jaclyn,NaN,Zhang,NaN,4364 Viera Avenue,NaN,Beaverton,Oregon,...,F,S,0,2,0,0,51859,2017-03-06,NaN,NaN
18359,14353,NaN,Erin,I,Reed,NaN,3866 Mt. Everest Court,NaN,Vancouver,British Columbia,...,F,S,0,0,0,0,87177,2017-03-06,NaN,NaN
18360,16676,NaN,Amanda,NaN,Perry,NaN,7870 Orangewood Dr.,NaN,Grossmont,California,...,F,M,1,2,0,0,136856,2017-03-06,NaN,NaN

In [8]:
df.drop(['Title','Suffix','Education','Occupation','PhoneNumber','MiddleName','AddressLine2'],axis=1,inplace=True)

In [9]:
df

,CustomerID,FirstName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,BirthDate,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated,BikeBuyer,AvgMonthSpend
0,21173,Chad,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1987-11-13,M,M,1,3,0,1,81916,2017-03-06,1.0,50.97
1,13249,Ryan,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,1972-07-21,M,M,1,2,1,2,81076,2017-03-06,1.0,53.11
2,29350,Julia,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,1985-11-09,F,S,0,3,0,0,86387,2017-03-06,1.0,54.08
3,13503,Theodore,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1977-10-18,M,M,1,2,1,2,61481,2017-03-06,1.0,56.93
4,22803,Marshall,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1975-02-05,M,S,1,1,0,0,51804,2017-03-06,1.0,55.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,Grace,Bailey,6627 Camelback Ct.,Coronado,California,United States,92118,1990-11-11,F,M,0,1,0,2,52953,2017-03-06,NaN,NaN
18357,11459,Tasha,Deng,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1992-10-13,F,S,0,2,0,0,60992,2017-03-06,NaN,NaN
18358,12160,Jaclyn,Zhang,4364 Viera Avenue,Beaverton,Oregon,United States,97005,1983-11-24,F,S,0,2,0,0,51859,2017-03-06,NaN,NaN
18359,14353,Erin,Reed,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,1995-06-15,F,S,0,0,0,0,87177,2017-03-06,NaN,NaN
18360,16676,Amanda,Perry,7870 Orangewood Dr.,Grossmont,California,United States,91941,1986-03-26,F,M,1,2,0,0,136856,2017-03-06,NaN,NaN

In [10]:
df.columns

Index(['CustomerID', 'FirstName', 'LastName', 'AddressLine1', 'City',
       'StateProvinceName', 'CountryRegionName', 'PostalCode', 'BirthDate',
       'Gender', 'MaritalStatus', 'HomeOwnerFlag', 'NumberCarsOwned',
       'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome', 'LastUpdated',
       'BikeBuyer', 'AvgMonthSpend'],
      dtype='object')

In [11]:
df.describe()

,CustomerID,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
count,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000,18355.00000,18355.000000
mean,20241.987092,0.610588,1.270301,0.338162,0.850389,72754.779642,0.55173,51.767207
std,5336.332731,0.487630,0.913989,0.568957,0.927315,30686.014313,0.49733,3.438024
min,11000.000000,0.000000,0.000000,0.000000,0.000000,25435.000000,0.00000,44.100000
25%,15621.000000,0.000000,1.000000,0.000000,0.000000,53312.000000,0.00000,49.410000
50%,20248.000000,1.000000,1.000000,0.000000,0.000000,61851.000000,1.00000,51.420000
75%,24863.000000,1.000000,2.000000,1.000000,2.000000,87410.000000,1.00000,53.600000
max,29483.000000,1.000000,5.000000,3.000000,3.000000,139115.000000,1.00000,65.290000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18361 entries, 0 to 18360
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            18361 non-null  int64
 1   FirstName             18361 non-null  object
 2   LastName              18361 non-null  object
 3   AddressLine1          18361 non-null  object
 4   City                  18361 non-null  object
 5   StateProvinceName     18361 non-null  object
 6   CountryRegionName     18361 non-null  object
 7   PostalCode            18361 non-null  object
 8   BirthDate             18361 non-null  object
 9   Gender                18361 non-null  object
 10  MaritalStatus         18361 non-null  object
 11  HomeOwnerFlag         18361 non-null  int64
 12  NumberCarsOwned       18361 non-null  int64
 13  NumberChildrenAtHome  18361 non-null  int64
 14  TotalChildren         18361 non-null  int64
 15  YearlyIncome          18361 non-null  int64
 16  LastUpdated           18361 non-null  object
 17  BikeBuyer             18355 non-null  float64
 18  AvgMonthSpend         18355 non-null  float64
dtypes: float64(2), int64(6), object(11)
memory usage: 2.7+ MB

In [13]:
#changing datatype for "BirthDate" and "LastUpdated"
df=df.astype({'BirthDate': 'datetime64[ns]'},copy=False)
df=df.astype({'LastUpdated': 'datetime64[ns]'},copy=False)

In [14]:
var_cat=[]
var_num=[]
for c in df.columns:
    if df[c].dtype=='object':
        var_cat.append(c)
    if (df[c].dtype=='int64'or df[c].dtype=='float64'):
         var_num.append(c)

print("Categorical Variables: ",var_cat)
print("Numerical variables: ",var_num)

Categorical Variables:  ['FirstName', 'LastName', 'AddressLine1', 'City', 'StateProvinceName', 'CountryRegionName', 'PostalCode', 'Gender', 'MaritalStatus']
Numerical variables:  ['CustomerID', 'HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome', 'BikeBuyer', 'AvgMonthSpend']

In [15]:
num_discrete=[]
num_continuous=[]
for c in var_num:
    if df[c].dtype=='int64':
        num_discrete.append(c)
    elif df[c].dtype=='float64':
        num_continuous.append(c)


print("Discrete variables: ",num_discrete)
print("Continuous variables: ",num_continuous)

Discrete variables:  ['CustomerID', 'HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome']
Continuous variables:  ['BikeBuyer', 'AvgMonthSpend']

In [16]:
Nomianls=['HomeOwnerFlag', 'BikeBuyer','CustomerID']
Ordinal=['NumberCarsOwned','NumberChildrenAtHome','TotalChildren','AvgMonthSpend','YearlyIncome']

# Q2

**(a)  Handling Null values**

In [17]:
df.isnull().sum()

CustomerID              0
FirstName               0
LastName                0
AddressLine1            0
City                    0
StateProvinceName       0
CountryRegionName       0
PostalCode              0
BirthDate               0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
LastUpdated             0
BikeBuyer               6
AvgMonthSpend           6
dtype: int64

In [18]:
df.dropna(axis=0,inplace=True)
df=df.astype({'BikeBuyer': 'int64'},copy=False)

In [19]:
df.isnull().sum()

CustomerID              0
FirstName               0
LastName                0
AddressLine1            0
City                    0
StateProvinceName       0
CountryRegionName       0
PostalCode              0
BirthDate               0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
LastUpdated             0
BikeBuyer               0
AvgMonthSpend           0
dtype: int64

**(b) Normalization**

In [20]:
# Normalizing by min max scaler
scaler=MinMaxScaler()
df[['YearlyIncome_normalized','AvgMonthSpend_normalized']]=scaler.fit_transform(df[num_continuous])

**(c) Discretization (Binning) on Continuous attributes or Categorical Attributes with too many different
values**

In [21]:
df['Male']=pd.get_dummies(df['Gender'],drop_first=True)

In [22]:
df['Single']=pd.get_dummies(df['MaritalStatus'],drop_first=True)

**(d) Standardization/Normalization**

In [23]:
# Normalizing by Z score
stdscaler=StandardScaler()

df[['YearlyIncome_std','AvgMonthSpend_std']]=stdscaler.fit_transform(df[num_continuous])

**(e) Binarization (One Hot Encoding)**

In [24]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder()
onehotencoder.fit_transform(df['HomeOwnerFlag'].values.reshape(-1,1))

<18355x2 sparse matrix of type '<class 'numpy.float64'>'
	with 18355 stored elements in Compressed Sparse Row format>

# Q3

**(a) Calculate Similarity in Simple Matching, Jaccard Similarity, and Cosine Similarity between two following objects of your transformed input data.**

In [25]:
# Jaccard Similarity = (number of observations in both sets) / (number in either set)
def jaccard(list1, list2):
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection
    return float(intersection) / union

In [26]:
jaccard(df['YearlyIncome'],df['AvgMonthSpend'])

0.0

In [27]:
jaccard(df['NumberChildrenAtHome'],df['BikeBuyer'])

5.448403617740002e-05

**(b) Calculate Correlation between two features Commute Distance and Yearly Income**

In [28]:
df['YearlyIncome'].corr(df['AvgMonthSpend'])

0.012202883547392651